### ISSUE TITLE
Incorrect usage of bold markdown

### ISSUE THREAD

**Issue by joshuan98** [AY2425S1-CS2113-W10-4/tp#105]
![image](https://github.com/user-attachments/assets/2829ba75-9f4e-4e5d-89c5-907ec7d7c1b7)

The bold markdown is not working

**Comment by Gao327** [comment]
![image](https://github.com/user-attachments/assets/b21947b5-bc16-4b3e-b358-7ce441309bf3)
I think this may a bug with the github webpage that it loads the markdown incorrectly. It may work if you try again.
