### ISSUE TITLE
[PE-D][Tester D] Sequence Diagram for hashCode()

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W10-4/tp#168]
![image.png](https://raw.githubusercontent.com/ehz0ah/ped/main/files/b2fb8f8a-17a0-4110-88d7-f4294b2592ad.png)

- There seems to be an extra Category instance here 
- The semicolon for class is also missing

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: ehz0ah/ped#8

**Comment by DanLinhHuynh-Niwashi** [comment]
Main should be :Main
