### ISSUE TITLE
[PE-D][Tester D] Confusing UI for add-expense

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W10-4/tp#170]
![image.png](https://raw.githubusercontent.com/ehz0ah/ped/main/files/2df82520-7deb-47c8-9585-19d6130e1df2.png)

- As per user guide, "Type 'yes' to create a new category or enter an existing category name:" was prompted. But upon keying a category that I thought may exist, it continues to say 'FnB' does not exist instead of 'games do not exist'

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ehz0ah/ped#10

**Comment by Oshen27** [comment]
Add 'no' to prompt to abort this command, show the new category name that the user types
